kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-b2bi-role-b2bi-612
  namespace: b2bi-612
rules:
  - apiGroups: ['route.openshift.io']
    resources: ['routes','routes/custom-host']
    verbs: ['get', 'watch', 'list', 'patch', 'update']
  - apiGroups: ['','batch']
    resources: ['secrets','configmaps','persistentvolumes','persistentvolumeclaims','pods','services','cronjobs','jobs']
    verbs: ['create', 'get', 'list', 'delete', 'patch', 'update']

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-b2bi-rolebinding-b2bi-612
  namespace: b2bi-612
subjects:
  - kind: ServiceAccount
    name: default
    namespace: b2bi-612
roleRef:
  kind: Role
  name: ibm-b2bi-role-b2bi-612
  apiGroup: rbac.authorization.k8s.io
  